In [2]:
import pandas as pd

data = {
    "gene": ["TAU", "APP", "BDNF"],
    "length": [6815, 3583, 873],
    "gc_content": [57.1, 48.5, 47.9]
}

df = pd.DataFrame(data)
print(df)
print(df.describe())

df[df["length"]>3000]

   gene  length  gc_content
0   TAU    6815        57.1
1   APP    3583        48.5
2  BDNF     873        47.9
            length  gc_content
count     3.000000    3.000000
mean   3757.000000   51.166667
std    2974.818986    5.147168
min     873.000000   47.900000
25%    2228.000000   48.200000
50%    3583.000000   48.500000
75%    5199.000000   52.800000
max    6815.000000   57.100000

  gene  length  gc_content
0  TAU    6815        57.1
1  APP    3583        48.5

In [6]:
import pandas as pd

data = {
    "gene": ["TAU", "APP", "BDNF"],
    "length": [6815, 3583, 873],
    "gc_content": [57.1, 48.5, 47.9]
}

df = pd.DataFrame(data)
df.sort_values("gc_content", ascending=False)

   gene  length  gc_content
0   TAU    6815        57.1
1   APP    3583        48.5
2  BDNF     873        47.9